### ISSUE TITLE
No melee damage reduction

### ISSUE THREAD

**Issue by pinksteven** [EvanoriMemoria/reincarnation-origins-broodmother#1]
broodmother doesn't have Too Many Legs/all legs power is not included in the broodmother.json file and it just doesn't exist in game

**Comment by EvanoriMemoria** [comment]
Thanks for the report! Not sure how I overlooked this, but it should be fixed as of commit [8ec9c03](https://github.com/EvanoriMemoria/reincarnation-origins-broodmother/commit/8ec9c03ee04a3e09461551b1cb224bbe5fc40dc5) Mod Version 1.0.1
